apiVersion: apps/v1
kind: Deployment
metadata:
  name: marlenejb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marlenejb
  template:
    metadata:
      labels:
        app: marlenejb
    spec:
      containers:
        - image: okteto.dev/marlenejb:latest
          name: marlenejb
          envFrom:
            - configMapRef:
                name: marlenejb-config
          livenessProbe:
            httpGet:
              path: /ht/
              port: 5080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: marlenejb
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "marlenejb"
      port: 5080
  selector:
    app: marlenejb
